# Generated by Django 4.1.4 on 2022-12-21 02:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goodBoard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='boards',
            name='id',
            field=models.CharField(max_length=10, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login', verbose_name='loginForeign')),
        ),
    ]
